/// 대시보드 인사말 기본 제공 문구 (영어)
///
/// 육아·집안일 팩은 미국 질병통제예방센터(CDC), 미국소아과학회(AAP),
/// 미국 농무부 식품안전검사국(USDA FSIS), 미국세정협회(ACI), 미국 환경보호청(EPA),
/// 아동권리보장원의 공개 가이드를 참고해 한 줄로 다듬은 것이다. 원문 인용이 아니라 요약이다.
///
/// 팩 ID는 [GreetingPackIds]와 반드시 일치해야 한다.
library;

const Map<String, List<String>> kGreetingPresetsEn = {
  'infant': [
    'Talk to your baby — your voice is the most calming thing they know',
    'When your baby makes a sound, echo it back and add a word',
    'Read to your baby every day — it builds language and sound awareness',
    'Sing to your baby and play music together',
    'Cuddling and skin-to-skin time gives your baby a sense of safety',
    'Play when your baby is awake, alert, and relaxed',
    'When your baby grabs something unsafe, redirect with a toy instead of scolding',
    "Never shake your baby — their neck can't support their head yet",
    'Always put your baby to sleep on their back — it lowers the risk of SIDS',
    'Babies 4–12 months need 12–16 hours of sleep a day, naps included',
    "Keep anything that could cover your baby's face out of reach",
    'Never carry hot food or drinks while holding your baby',
    'Cut food into small bites to prevent choking',
    'Keep your home and car free of secondhand smoke',
    'Ride with a rear-facing car seat in the back seat, every time',
    'Keep vaccinations on schedule',
    'Feed slowly and patiently; offer new tastes without forcing them',
    'Give plenty of floor time — it builds strength and curiosity',
    "Don't leave your baby in swings, bouncers, or walkers for long stretches",
    "Look after yourself too — it's easier to enjoy your baby when you feel well",
  ],
  'toddler': [
    'Ask your toddler to find objects or name body parts',
    'Play matching games like shape sorters and simple puzzles',
    'Build on the words your toddler starts with to stretch them into sentences',
    'Let them help dress and feed themselves — independence grows there',
    "Respond to the behavior you want more than you punish the behavior you don't",
    'Whenever you say no, always show what to do instead',
    "Small outings — a park trip, a bus ride — feed your toddler's curiosity",
    'Set aside a reading time every day',
    'Let pretend play run free — it is real learning',
    'Encourage your child to say their own name and age',
    'Sing simple songs and nursery rhymes together',
    'Give attention and praise for following instructions; give less to tantrums',
    'Teach acceptable ways to show that they are upset',
    'Never leave a toddler near water — bath, pool, or pond — unwatched',
    'Gate the stairs and cover unused electrical outlets',
    'Turn pot handles inward; keep irons and heaters out of reach',
    'Lock up medicines, cleaners, and poisons',
    'Never leave your toddler alone in a vehicle, even for a moment',
    'Have your toddler sit while eating and chew thoroughly',
    'Offer water and plain milk instead of sugary drinks',
    'Offer a selection of healthy foods and let them choose',
    'Keep offering new foods — liking them can take many tries',
    'Toddlers 1–3 need 11–14 hours of sleep a day, naps included',
    'Cap screen time at about an hour a day and keep TVs out of the bedroom',
  ],
  'preschool': [
    'Keep reading together, and visit the library or a bookstore',
    'Let your child help with simple chores',
    'Be clear and consistent: explain and show the behavior you expect',
    'Follow every "no" with what they should be doing instead',
    'Speak in full sentences and grown-up words to grow their language',
    'Walk your child through the steps of solving a problem when they are upset',
    'Give a small number of simple choices — what to wear, eat, or play',
    'Make time with other children — that is where sharing and friendship are learned',
    'Teach your child to stay out of traffic and never chase a ball into the street',
    'Keep trikes on the sidewalk and always put a helmet on',
    'Check playground equipment for loose parts and sharp edges',
    'Teach swimming, but watch your child near water at all times',
    'Teach your child how to be safe around strangers',
    'Eat together when you can — let them see you enjoying good food',
    'Limit foods and drinks high in added sugar, solid fat, or salt',
    'Provide age-appropriate play gear, and let your preschooler pick the game',
    'Preschoolers need 10–13 hours of sleep a day, naps included',
    'Keep screen time to about an hour a day and TVs out of the bedroom',
    'Use the car seat up to its height and weight limit, then move to a booster',
    'Answer the "why" questions — that is learning happening out loud',
  ],
  'school': [
    'Talk through the choices in a hard situation and where each one leads',
    'Agree on family expectations and reasonable consequences in advance',
    'Let privileges grow together with responsibility',
    'Rule out physical punishment — it teaches fear, not judgment',
    'Keep family rules short and positive: "We say please when we ask"',
    'Household routines and turns make school routines easier too',
    'Share regular family meals — belonging grows at the table',
    'Keep family rituals — birthdays, movie nights, weekend rides',
    "Tune in to your child's interests and ask about them",
    'Praise good behavior specifically: "You cleaned your room — thank you"',
    'Ignoring minor, harmless misbehavior is a legitimate strategy',
    "Hear your child's whole explanation before you solve anything",
    'School-age children need 9–12 hours of sleep a night',
    'Turn screens off an hour before bed and keep them out of the bedroom',
    'Keep wake and bedtimes about the same on weekends too',
    'Make a family media plan together',
    'When you handle something badly, apologize first — they are watching',
    "Don't do the homework — ask where they got stuck",
    'Listen to friendship troubles without judging',
    'Once a day, give your child your full, undistracted attention',
  ],
  'teen': [
    'Listen without judging — what you say matters less than that you listen',
    'Hold back your first reaction — that is where conversations die',
    "Don't catastrophize — it only makes your teen more anxious",
    "Don't over-empathize either — many teen feelings are passing ones",
    'Have a conversation, not a lecture — lectures do not stick',
    'Share your values without sounding judgmental',
    'Concrete examples land; abstract advice does not',
    'Start these talks early and often, long before there is a problem',
    'Set rules together: name the problem, list options, choose, try, renegotiate',
    'What teens need most is connection, not control',
    'Give unconditional support and clear boundaries at the same time',
    "Respect your teen's opinion and never play down their worries",
    'Create chances for them to use their own judgment; stay available for advice',
    "Get to know your teen's friends",
    "Show interest in your teen's school and activities",
    'Keep showing affection — they still need it, however grown they look',
    'Watch for changes in behavior, and ask directly if they seem down',
    'Teens need 8–10 hours of sleep a night',
    'Keep screens out of the bedroom at night',
    'Acknowledge good choices and real effort when you see them',
  ],
  'parenting': [
    'A child is an individual person who deserves respect',
    'Know your child: temperament and pace of development differ for every child',
    'Look at yourself first — your own patterns shape the room',
    'Change the angle — the same behavior looks different from another side',
    'Grow together — your role should change as your child changes',
    'Be fully present — when you are together, be only there',
    'Listen and empathize — take in what they say and meet the feeling',
    'Stay consistent — keep the promises and rules you agreed on',
    'Own your mistakes — apologize when you get it wrong',
    'Raise together — ask for help from people around you and from professionals',
    'Children copy what you do, not what you say',
    'Praise the effort, not the result: "You worked hard on that"',
    'Your attention is the most powerful reward you have',
    'Prepare your child in advance for situations that usually go wrong',
    'If you feel out of control, give yourself the time-out first',
    'If you handled it badly, apologize and say what you will do next time',
    'Rules only work when every caregiver keeps the same ones',
    'Play is not a break from learning — it is the learning',
    'The more they explore with all five senses, the more curiosity grows',
    'When you are well, they are well — caring for yourself is part of parenting',
  ],
  'quote': [
    'A journey of a thousand miles begins with a single step — Tao Te Ching',
    'Great vessels take the longest to complete — Tao Te Ching',
    'Learning without thinking leaves you with nothing — Confucius, Analects',
    'Among any three people walking, one has something to teach me — Analects',
    'Going too far is the same as falling short — Confucius, Analects',
    'Knowing is less than loving; loving is less than delighting in it — Analects',
    'Piled-up earth becomes a mountain; gathered water becomes a sea — Xunzi',
    'It takes a village to raise a child — African proverb',
    'If you want to go fast, go alone; to go far, go together — African proverb',
    'Fall seven times, stand up eight — Japanese proverb',
    'Make haste slowly — Latin proverb',
    'Starting is half the work — Korean proverb',
    'Specks of dust pile into a mountain — Korean proverb',
    'After the hardship comes the sweetness — Korean proverb',
    'No tree withstands ten swings of the axe — Korean proverb',
    'The bigger the hurry, the longer the way around — Korean proverb',
    'Even a sheet of paper is lighter when two lift it — Korean proverb',
    'Kind words going out bring kind words back — Korean proverb',
    "Don't put off what today can carry",
    'Without haste, but without rest',
    "The only fair comparison is yesterday's you",
    'Habit becomes a second nature',
    'Consistent days beat perfect ones',
    'The best time is right now',
  ],
  'cheer': [
    "You're doing enough today",
    "It doesn't have to be perfect — you're getting it done",
    "A short break won't ruin the day",
    'You take care of everyone — you deserve care too',
    'A little better than yesterday is a win',
    'On hard days, be kind to yourself first',
    'Finish one thing today and today counts as a win',
    "Here's to your day",
    'You do not have to be good at all of it',
    'Asking for help is not weakness — it is good judgment',
    "Right now, you are someone's whole world",
    "What didn't get done today can belong to tomorrow",
    'Sleeping and eating well are real items on the list',
    'Put comparison down and go at your own pace',
    "You are the one who will remember your child's today",
    'A good parent is not a perfect one — just one who shows up',
    'If you are angry, it is okay to pause',
    'Give yourself credit for the small things you finished',
    'If there was one moment of laughter today, that is enough',
    'You do not have to carry all of it alone',
    'Hard stretches pass — this is not forever',
    'Drink a glass of water and take one deep breath',
    'Someone should tell you that you did well today — so, you did',
    'Tomorrow gets to start over',
  ],
  'choreKitchen': [
    'Keep the fridge at 40°F (4°C) or below and the freezer at 0°F (-18°C) or below',
    'Refrigerate perishables within 2 hours — 1 hour if it is above 90°F (32°C)',
    'Bacteria multiply fastest between 40–140°F (4–60°C), doubling in as little as 20 minutes',
    'Leftovers keep 3–4 days in the fridge, 3–4 months in the freezer',
    'Divide large amounts into shallow containers so they cool quickly',
    'Wash hands with soap and warm water for 20 seconds before and after handling food',
    'Seal raw meat and seafood so their juices never touch other food',
    'Thaw in the fridge, in cold water, or in the microwave — never on the counter',
    'Keep separate cutting boards for raw meat and for produce',
    'Sanitize cutting boards with 1 tablespoon of unscented bleach per gallon (about 4L) of water',
    "Don't rinse raw meat — splashing spreads bacteria around the sink",
    'Check doneness with a thermometer, not by color',
    'Put a thermometer in the fridge to know its real temperature',
    'Pick up chilled and frozen items last when you shop',
    "Don't leave hot food out to cool for long — refrigerate it while it's still warm",
    'Boil or replace dish cloths often',
    'Move opened canned food into a sealed container instead of storing it in the can',
    "Don't pack the fridge full — cold air needs room to circulate",
    'Judge food by how it was stored, not only by the date on the package',
    'Freezing pauses bacteria — it does not kill them',
    'Reheat leftovers until they are steaming hot all the way through',
    'When in doubt, throw it out — you cannot smell most foodborne bacteria',
  ],
  'choreLaundry': [
    'Check the care label before you wash anything',
    'Sort into loads that need the same detergent, cycle, and water temperature',
    'Wash new, dark, or bright items separately the first few times',
    "Use the warmest water that's safe for the fabric",
    "More detergent isn't better — follow the amount on the package",
    'Use less detergent for small loads, light soil, or soft water',
    "Don't overload the washer — clothes need room to move",
    'Treat a stain right away — the longer it sits, the harder it gets',
    'When in doubt, rinse or soak in cold water before treating',
    'Pretreating before a stain dries or sets is what makes it come out',
    "If a stain survived the wash, don't dry it — heat sets the stain permanently",
    'Zip zippers and unbutton buttons before washing',
    'Empty pockets and turn clothes inside out to reduce pilling',
    'Put delicates like underwear and knits in a mesh bag',
    'Take the load out as soon as it finishes — sitting wet is what causes the smell',
    'Leave the washer door open after use so the drum dries out',
    'Dry knits flat instead of hanging them',
    'Clean the dryer lint filter every single load',
    'Go easy on fabric softener with towels — it reduces absorbency',
    'Match the iron temperature to what the care label allows',
  ],
  'choreCleaning': [
    'Never mix bleach with any other cleaner — the fumes can be dangerous to breathe',
    'Bleach plus ammonia makes chlorine and chloramine gas that can damage lung tissue',
    'Open windows and doors for ventilation whenever you use bleach indoors',
    'Clean visibly dirty surfaces with soap or detergent before you disinfect',
    'Use regular unscented bleach with 5–9% sodium hypochlorite',
    'Mix about 1/3 cup of bleach per gallon (4L) of room-temperature water',
    'Leave the surface visibly wet for at least one minute for the disinfectant to work',
    'Diluted bleach loses strength after 24 hours — mix only what you will use today',
    'Wash your hands after cleaning or disinfecting',
    'Store cleaners and hand sanitizer out of reach of children and pets',
    'The key to mold control is moisture control',
    'Keep indoor humidity below 60%, ideally between 30% and 50%',
    'Dry water-damaged areas within 24–48 hours to keep mold from growing',
    'Fix plumbing leaks as soon as you find them',
    'Run the exhaust fan while showering, cooking, or running the dishwasher',
    "Don't paint or caulk over mold — clean it off first",
    'Clean the mold but not the water problem, and the mold comes back',
    'Wear gloves, goggles, and an N-95 mask when cleaning mold',
    'Absorbent things like carpet or ceiling tiles usually need replacing, not cleaning',
    'Insulating cold water pipes cuts down on condensation',
  ],
  'englishDaily': [
    "Let's call it a day. — wrapping up for the day",
    "I'm on my way. — you've already left",
    "It's on me. — you're paying",
    'Let me get back to you. — you need time before answering',
    'That works for me. — agreeing to a plan or time',
    'I could use a hand. — asking for help politely',
    'Take your time. — telling someone not to rush',
    'It slipped my mind. — you forgot something',
    'Long story short, — skipping to the point',
    "I'm not following. — you didn't understand",
    'Sounds good to me. — agreeing casually',
    'Never mind. — dropping what you just said',
    'Just in case. — explaining a precaution',
    "I'll pass this time. — declining politely",
    "It's up to you. — leaving the choice to them",
    'My bad. — admitting a small mistake',
    "Let's play it by ear. — deciding later as things go",
    "I'm running late. — you won't arrive on time",
    'Could you say that again? — asking someone to repeat',
    'That makes sense. — showing you understand',
    'Give me a second. — asking for a short pause',
    'Same here. — you feel the same way',
  ],
  'englishTravel': [
    'Could I get the check, please? — asking for the bill',
    'Do you have a table for two? — walking into a restaurant',
    'I have a reservation under Kim. — checking in for a booking',
    'What do you recommend? — asking staff to suggest',
    'Can I get this to go? — ordering takeout',
    'Could I have some water, please? — asking for water',
    "I'm allergic to nuts. — telling staff about an allergy",
    'Not too spicy, please. — adjusting your order',
    'Where is the nearest station? — asking for directions',
    'Does this bus go downtown? — checking a route',
    'How much is it to the airport? — asking a taxi fare',
    'Could you take a picture of us? — asking a stranger for a photo',
    "I'd like to check in. — arriving at a hotel",
    'What time is checkout? — asking the hotel',
    'Is breakfast included? — checking what the rate covers',
    'Do you have Wi-Fi? — asking about internet',
    "I'm just looking, thanks. — declining a shop assistant",
    'Can I try this on? — asking to use a fitting room',
    'Do you take cards? — asking about payment',
    "I think I'm lost. — asking for help finding your way",
  ],
  'englishWork': [
    "Let's touch base next week. — scheduling a follow-up",
    'Just a quick heads-up. — warning someone in advance',
    "I'm circling back on this. — following up on an old thread",
    "I'll loop you in. — adding someone to the thread",
    'Can we push it to Friday? — asking to move a deadline',
    "I'm swamped today. — you're overloaded",
    "Let's take this offline. — moving a topic out of a meeting",
    'Sorry for the late reply. — opening a delayed email',
    'Please find the file attached. — sending an attachment',
    'Thanks for the quick turnaround. — thanking fast work',
    'Does Tuesday work for you? — proposing a time',
    "I'll keep you posted. — promising updates",
    "Let me know if anything's unclear. — closing an explanation",
    'Could you walk me through it? — asking for a step-by-step',
    "We're on the same page. — confirming shared understanding",
    "I'll take care of it. — taking ownership of a task",
    'Could you double-check this? — asking for a review',
    "Let's set up a quick call. — suggesting a short call",
    'Apologies for the confusion. — correcting a misunderstanding',
    'Looking forward to hearing from you. — closing an email',
  ],
};
